/**
 * Settings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ParamCombineeBesoinDTO } from './paramCombineeBesoinDTO';


export interface BesoinDTO {
    id?: number;
    nom: BesoinDTO.NomEnum;
    ordre: number;
    besoinType: BesoinDTO.BesoinTypeEnum;
    impactStatusSimples?: Array<ParamCombineeBesoinDTO>;
    mutualExclusions?: Array<BesoinDTO.MutualExclusionsEnum>;
}
export namespace BesoinDTO {
    export type NomEnum = 'TRAD' | 'TELEMED' | 'MEDFAM' | 'RESSOIN' | 'CONSMED' | 'TIERSGARANT' | 'GLOBAL' | 'GLOBAL_CLASSIC' | 'IND_GLOBAL' | 'GLOBAL_MIPRIVEE' | 'GLOBAL_PRIVEE' | 'SOINS_AMBULATOIRE' | 'CHOIX_SPECIALISTE' | 'CHOIX_ETABLISSEMENT' | 'VOYAGES_SEJOUR' | 'SOINS_DENTAIRES' | 'MED_ALTERNATIVES' | 'COMPL_ACCIDENT' | 'RENTES_CAPITAUX' | 'PROT_JURIDIQUE';
    export const NomEnum = {
        TRAD: 'TRAD' as NomEnum,
        TELEMED: 'TELEMED' as NomEnum,
        MEDFAM: 'MEDFAM' as NomEnum,
        RESSOIN: 'RESSOIN' as NomEnum,
        CONSMED: 'CONSMED' as NomEnum,
        TIERSGARANT: 'TIERSGARANT' as NomEnum,
        GLOBAL: 'GLOBAL' as NomEnum,
        GLOBALCLASSIC: 'GLOBAL_CLASSIC' as NomEnum,
        INDGLOBAL: 'IND_GLOBAL' as NomEnum,
        GLOBALMIPRIVEE: 'GLOBAL_MIPRIVEE' as NomEnum,
        GLOBALPRIVEE: 'GLOBAL_PRIVEE' as NomEnum,
        SOINSAMBULATOIRE: 'SOINS_AMBULATOIRE' as NomEnum,
        CHOIXSPECIALISTE: 'CHOIX_SPECIALISTE' as NomEnum,
        CHOIXETABLISSEMENT: 'CHOIX_ETABLISSEMENT' as NomEnum,
        VOYAGESSEJOUR: 'VOYAGES_SEJOUR' as NomEnum,
        SOINSDENTAIRES: 'SOINS_DENTAIRES' as NomEnum,
        MEDALTERNATIVES: 'MED_ALTERNATIVES' as NomEnum,
        COMPLACCIDENT: 'COMPL_ACCIDENT' as NomEnum,
        RENTESCAPITAUX: 'RENTES_CAPITAUX' as NomEnum,
        PROTJURIDIQUE: 'PROT_JURIDIQUE' as NomEnum
    }
    export type BesoinTypeEnum = 'LAMAL' | 'LCA_SIMPLE' | 'LCA_COMBINEE';
    export const BesoinTypeEnum = {
        LAMAL: 'LAMAL' as BesoinTypeEnum,
        LCASIMPLE: 'LCA_SIMPLE' as BesoinTypeEnum,
        LCACOMBINEE: 'LCA_COMBINEE' as BesoinTypeEnum
    }
    export type MutualExclusionsEnum = 'TRAD' | 'TELEMED' | 'MEDFAM' | 'RESSOIN' | 'CONSMED' | 'TIERSGARANT' | 'GLOBAL' | 'GLOBAL_CLASSIC' | 'IND_GLOBAL' | 'GLOBAL_MIPRIVEE' | 'GLOBAL_PRIVEE' | 'SOINS_AMBULATOIRE' | 'CHOIX_SPECIALISTE' | 'CHOIX_ETABLISSEMENT' | 'VOYAGES_SEJOUR' | 'SOINS_DENTAIRES' | 'MED_ALTERNATIVES' | 'COMPL_ACCIDENT' | 'RENTES_CAPITAUX' | 'PROT_JURIDIQUE';
    export const MutualExclusionsEnum = {
        TRAD: 'TRAD' as MutualExclusionsEnum,
        TELEMED: 'TELEMED' as MutualExclusionsEnum,
        MEDFAM: 'MEDFAM' as MutualExclusionsEnum,
        RESSOIN: 'RESSOIN' as MutualExclusionsEnum,
        CONSMED: 'CONSMED' as MutualExclusionsEnum,
        TIERSGARANT: 'TIERSGARANT' as MutualExclusionsEnum,
        GLOBAL: 'GLOBAL' as MutualExclusionsEnum,
        GLOBALCLASSIC: 'GLOBAL_CLASSIC' as MutualExclusionsEnum,
        INDGLOBAL: 'IND_GLOBAL' as MutualExclusionsEnum,
        GLOBALMIPRIVEE: 'GLOBAL_MIPRIVEE' as MutualExclusionsEnum,
        GLOBALPRIVEE: 'GLOBAL_PRIVEE' as MutualExclusionsEnum,
        SOINSAMBULATOIRE: 'SOINS_AMBULATOIRE' as MutualExclusionsEnum,
        CHOIXSPECIALISTE: 'CHOIX_SPECIALISTE' as MutualExclusionsEnum,
        CHOIXETABLISSEMENT: 'CHOIX_ETABLISSEMENT' as MutualExclusionsEnum,
        VOYAGESSEJOUR: 'VOYAGES_SEJOUR' as MutualExclusionsEnum,
        SOINSDENTAIRES: 'SOINS_DENTAIRES' as MutualExclusionsEnum,
        MEDALTERNATIVES: 'MED_ALTERNATIVES' as MutualExclusionsEnum,
        COMPLACCIDENT: 'COMPL_ACCIDENT' as MutualExclusionsEnum,
        RENTESCAPITAUX: 'RENTES_CAPITAUX' as MutualExclusionsEnum,
        PROTJURIDIQUE: 'PROT_JURIDIQUE' as MutualExclusionsEnum
    }
}
