/**
 * Settings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ErrorReasonDetailsRootCause } from './errorReasonDetailsRootCause';


export interface ErrorReasonDetails {
    /**
     * the business error code associates with the error
     */
    businessErrorCode?: number;
    /**
     * the timestamp associated with the error
     */
    timestamp?: number;
    /**
     * the http status code
     */
    status?: number;
    /**
     * the message associated with the error
     */
    error?: string;
    /**
     * the message of the original exception
     */
    exception?: string;
    /**
     * human readable message associated to the error
     */
    message?: string;
    /**
     * the stack trace of the exception
     */
    trace?: string;
    /**
     * the path in the URI
     */
    path?: string;
    rootCause?: ErrorReasonDetailsRootCause;
}
