/**
 * Settings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GraphPartItemDTO } from './graphPartItemDTO';
import { I18nDTO } from './i18nDTO';


/**
 * represents an edge on the graph. In a survey, an edge is a possible response to go from a question to another one.
 */
export interface GraphEdgeDTO extends GraphPartItemDTO {
    /**
     * unique identifier of the source vertice
     */
    source: number;
    /**
     * unique identifier of the destination vertice
     */
    destination: number;
    /**
     * the weight of the edge. This weight is added to the path weight and a path weight is unique on the graph.
     */
    weight: number;
}
