/**
 * Settings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertiesDTO } from './propertiesDTO';


export interface I18nDTO {
    /**
     * the unique id of the i118n
     */
    id?: string;
    /**
     * the iso code 2 of tthe lang
     */
    lang?: string;
    properties?: Array<PropertiesDTO>;
}
