/**
 * Settings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ParamCombineeBesoinDTO {
    nom: ParamCombineeBesoinDTO.NomEnum;
    statut: ParamCombineeBesoinDTO.StatutEnum;
}
export namespace ParamCombineeBesoinDTO {
    export type NomEnum = 'TRAD' | 'TELEMED' | 'MEDFAM' | 'RESSOIN' | 'CONSMED' | 'TIERSGARANT' | 'GLOBAL' | 'GLOBAL_CLASSIC' | 'IND_GLOBAL' | 'GLOBAL_MIPRIVEE' | 'GLOBAL_PRIVEE' | 'SOINS_AMBULATOIRE' | 'CHOIX_SPECIALISTE' | 'CHOIX_ETABLISSEMENT' | 'VOYAGES_SEJOUR' | 'SOINS_DENTAIRES' | 'MED_ALTERNATIVES' | 'COMPL_ACCIDENT' | 'RENTES_CAPITAUX' | 'PROT_JURIDIQUE';
    export const NomEnum = {
        TRAD: 'TRAD' as NomEnum,
        TELEMED: 'TELEMED' as NomEnum,
        MEDFAM: 'MEDFAM' as NomEnum,
        RESSOIN: 'RESSOIN' as NomEnum,
        CONSMED: 'CONSMED' as NomEnum,
        TIERSGARANT: 'TIERSGARANT' as NomEnum,
        GLOBAL: 'GLOBAL' as NomEnum,
        GLOBALCLASSIC: 'GLOBAL_CLASSIC' as NomEnum,
        INDGLOBAL: 'IND_GLOBAL' as NomEnum,
        GLOBALMIPRIVEE: 'GLOBAL_MIPRIVEE' as NomEnum,
        GLOBALPRIVEE: 'GLOBAL_PRIVEE' as NomEnum,
        SOINSAMBULATOIRE: 'SOINS_AMBULATOIRE' as NomEnum,
        CHOIXSPECIALISTE: 'CHOIX_SPECIALISTE' as NomEnum,
        CHOIXETABLISSEMENT: 'CHOIX_ETABLISSEMENT' as NomEnum,
        VOYAGESSEJOUR: 'VOYAGES_SEJOUR' as NomEnum,
        SOINSDENTAIRES: 'SOINS_DENTAIRES' as NomEnum,
        MEDALTERNATIVES: 'MED_ALTERNATIVES' as NomEnum,
        COMPLACCIDENT: 'COMPL_ACCIDENT' as NomEnum,
        RENTESCAPITAUX: 'RENTES_CAPITAUX' as NomEnum,
        PROTJURIDIQUE: 'PROT_JURIDIQUE' as NomEnum
    }
    export type StatutEnum = 'LOCKED' | 'DISABLED';
    export const StatutEnum = {
        LOCKED: 'LOCKED' as StatutEnum,
        DISABLED: 'DISABLED' as StatutEnum
    }
}
