/**
 * Settings API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TarifLightDTO {
    defautTarifCombination?: boolean;
    codeProduit?: string;
    codeCaisse?: string;
    codeFranchise?: string;
    franchise?: number;
    codeVariante?: string;
    accident?: boolean;
    codeRisque?: string;
    montant?: number;
    codeCritereSupplementaire1?: string;
    codeCritereSupplementaire2?: string;
}
